image: desertbit/golang-gb

pipelines:
  default:
    - step:
        script:
          - go get github.com/Sirupsen/logrus
          - go get github.com/influxdata/influxdb/client/v2
          - go get github.com/oliveagle/jsonpath
          - go get github.com/gorilla/mux
          - env GOOS=linux GOARCH=amd64 go build -v
