image: desertbit/golang-gb

pipelines:
  default:
    - step:
        script:
          - go get github.com/Sirupsen/logrus
          - go get github.com/prometheus/client_golang/prometheus
          - go get gopkg.in/xmlpath.v2
          - go get github.com/gorilla/mux
          - go build -v